pull_request_rules:
#  - name: Automatic merge to master on successful build if it's not WIP
#    conditions:
#      - base=master
#      - check-success=build
#      - check-success=test
#      - -title~=(?i)wip
#    actions:
#      merge:
#        method: merge
#      assign:
#        add_users:
#          - 5h15h4k1n9
  - name: Add `kotlin` label, if files associated with Kotlin were changed
    conditions:
      - or:
        - files~=\.kt$
        - files~=\.kts$
    actions:
      label:
        add:
          - kotlin
  - name: Add `Dockerfile` label, if Dockerfile was changed
    conditions:
      - files~=\Dockerfile$
    actions:
      label:
        add:
          - Dockerfile
