version: '3'

services:
  mysql_host:
    image: mysql:8.0
    restart: always

    environment:
      MYSQL_USER: testsys
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: testsys_db
      MYSQL_PASSWORD: p@ssw0rd

    ports:
      - "3306:3306"
    expose:
      - "3306"

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

    volumes:
      - ./data/mysql:/var/lib/mysql

#  web-client:
#    image: testsystrik/trik-testsys-web-client:2.0.0-alpha.37
#    restart: always
#
#    environment:
#      - JAVA_OPTIONS=-server -Xmx8g -Xms1g -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/web-client/dumps/ -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=20 -XX:ConcGCThreads=10 -XX:InitiatingHeapOccupancyPercent=70
#
#    ports:
#      - "8888:8888"
#    expose:
#      - "8888"
#
#    volumes:
#      - ./logs/web-client:/web-client/logs
#      - ./data:/web-client/data
#      - ./dumps:/web-client/dumps
#    links:
#      - mysql_host:mysql_host
