version: '3'

services:
  mysql_host:
    image: mysql:9.1.0
    restart: always

    environment:
      MYSQL_USER: testsys
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: testsys_db
      MYSQL_PASSWORD: p@ssw0rd

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

    volumes:
      - ./data/mysql:/var/lib/mysql

  web-client:
    image: testsystrik/trik-testsys-web-client:2.2.1
    restart: always

    environment:
      - JAVA_OPTIONS=-server -Xmx4g -Xms1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/web-client/dumps/ -XX:+CrashOnOutOfMemoryError -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=6 -XX:ConcGCThreads=3
      - TRIK_STUDIO_VERSION=latest
      - GRADING_NODE_ADDRESSES=1.1.1.1:8080,2.2.2.2:8080,3.3.3.3:8080
      - CONTEXT_PATH=/demo2025
      - MYSQL_HOST=mysql_host
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=testsys
      - MYSQL_PASSWORD=p@ssw0rd

    ports:
      - "8888:8888"
    expose:
      - "8888"

    volumes:
      - ./logs/web-client:/web-client/logs
      - ./data:/web-client/data
      - ./dumps:/web-client/dumps
    links:
      - mysql_host:mysql_host

    depends_on:
      mysql_host:
        condition: service_healthy