version: '3'

services:
  mysql_host:
    image: mysql
    restart: always

    environment:
      MYSQL_USER: testsys
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: testsys_db
      MYSQL_PASSWORD: p@ssw0rd

    ports:
      - "3306:3306"
    expose:
      - "3306"

    volumes:
      - ./data/mysql:/var/lib/mysql

  web-client:
    image: testsystrik/trik-testsys-web-client:2.0.0-alpha.1
    restart: always

    ports:
      - "8888:8888"
    expose:
      - "8888"

    volumes:
      - ./logs/web-client:/web-client/logs
      - ./data:/web-client/data
    links:
      - mysql_host:mysql_host