version: '3.1'

services:
  db:
    image: mysql
    restart: always

    environment:
      MYSQL_USER: testsys
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: testsys_db
      MYSQL_PASSWORD: p@ssw0rd

    ports:
      - "3306:3306"
    expose:
      - "3306"

#    volumes:
#      - /Users/shisha/Projects/Kotlin/trik-testsys-task-uploader/data:/var/lib/mysql