spring:
  jpa:
    hibernate:
      ddl-auto: update                                          # Update database schema on start if necessary
    open-in-view: on                                            # Enable JPA open-in-view
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql_host}:3306/testsys_db   # Database URL
    username: testsys                                           # Database username
    password: p@ssw0rd                                          # Database password
    driver-class-name: com.mysql.cj.jdbc.Driver                 # Driver for MySQL
  h2:
    console:
      enabled: off                                              # Disable H2 console
  sql:
    init:
      mode: never
logging:
  file:
    name: "${PWD}/logs/server.log"                                   # Path to log file
  logback:
    rollingpolicy:
      clean-history-on-start: false                             # Not cleaning history on start
      max-history: 31                                           # Stores a month of logs
server:
  port: 8888                                                    # Entrypoint

path:
  l10n: "${PWD}/src/main/resources/static/l10n"

app:
  version: 1.0.2
  grading-system:
    path: http://grading-system:8080/v3/grading-system
  testsys:
    api:
      prefix: /demo2024
    paths:
      submission: "${PWD}/submissions"
      training: "${PWD}/training"
      benchmark: "${PWD}/benchmark"
  avatar:
    path: "${PWD}/src/main/resources/static/avatars"
  utc:
    plus: 3