spring:
  jpa:
    hibernate:
      ddl-auto: update                                          # Update database schema on start if necessary
    open-in-view: on                                            # Enable JPA open-in-view
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/testsys_db   # Database URL
    username: testsys                                           # Database username
    password: p@ssw0rd                                          # Database password
    driver-class-name: com.mysql.cj.jdbc.Driver                 # Driver for MySQL
    hikari:
      connection-timeout: 30000                                 # Connection timeout
      maximum-pool-size: 20                                     # Maximum pool size
      initialization-fail-timeout: 0                            # Initialization fail timeout
      max-lifetime: 1800000                                     # Maximum lifetime
      idle-timeout: 600000                                      # Idle timeout
      minimum-idle: 5                                           # Minimum idle
  h2:
    console:
      enabled: off                                              # Disable H2 console
  sql:
    init:
      mode: never
  data:
    jdbc:
      repositories:
        enabled: false                                           # Disable JDBC repositories
logging:
  file:
    name: "${PWD}/app-test/logs/server.log"                              # Path to log file
  logback:
    rollingpolicy:
      clean-history-on-start: false                             # Not cleaning history on start
      max-history: 31                                           # Stores a month of logs
server:
  port: 8888                                                    # Entrypoint
  servlet:
    context-path: /2024
    session:
      timeout: 3h
  error:
    whitelabel:
      enabled: false
    include-message: always

path:
  l10n: "${PWD}/app-test/src/main/resources/static/l10n"
  startup:
    entities: "${PWD}/app-test/data/entities/"
    nodes: "${PWD}/app-test/data/nodes/"
  taskFiles:
    solutions: "${PWD}/app-test/data/taskFiles/solutions/"
    polygons: "${PWD}/app-test/data/taskFiles/polygons/"
    exercises: "${PWD}/app-test/data/taskFiles/exercises/"
    conditions: "${PWD}/app-test/data/taskFiles/conditions/"
  files:
    solutions: "${PWD}/app-test/data/files/solutions/"
    verdicts: "${PWD}/app-test/data/files/verdicts/"
    recordings: "${PWD}/app-test/data/files/recordings/"
    results: "${PWD}/app-test/data/files/results/"

trik:
  studio:
    version: "testsystrik/trik-studio:release-2023.1-2024-10-10-2.0.0"