name: Configure Git
description: Adds the necessary configurations to Git
inputs:
  user-name:
    description: 'The name of the user'
    required: true
  user-mail:
    description: 'The email of the user'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Git
      shell: bash
      run: |
        git config --global user.name "${{ inputs.user-name }}"
        git config --global user.email "${{ inputs.user-mail }}"
